services:
    Cethyworks\GooglePlaceAutocompleteBundle\Command\GooglePlaceAutocompleteLibraryCommand:
        arguments:
            - "@twig"
            - "%cethyworks.google_place_autocomplete.google_api_key%"

    Cethyworks\GooglePlaceAutocompleteBundle\Form\Extension\GooglePlaceAutocompleteInjectorAwareTypeExtension:
        arguments:
            - "@Cethyworks\\ContentInjectorBundle\\EventSubscriber\\ContentInjectorSubscriber"
            - "@Cethyworks\\GooglePlaceAutocompleteBundle\\Command\\GooglePlaceAutocompleteLibraryCommand"
        tags:
            # priority -10 ensure call after InjectorAwareTypeExtension
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType, priority: -10 }
